name: DOUBLE DUTCH CREATIVE
favicon: null
layout_spectrum: 0.5651141605339944
typography_spectrum: 0.06694955984130502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08922536578029394
  lightness: 0.6214876873418689
  saturation: 0.22276016674004495
  rhythmicContrast: 0.31387296435423195
purpose: []
